DiscordBot.DataAccess/EventsSheetsInitialisationException.cs, DiscordBot.DataAccess/EventsSheetsService.cs
To do this: add tracking of largest key in use, and get this from the
sheet on service construction. Also, add a dictionary to map between
event keys and rows; this will come in useful when editing and
deleting events, and make sure the event adding method keeps these
up to date.
For context, when events are deleted either the will be blank rows in
the sheet, or the event key will not correspond to the row number of
the event. I chose the second option, so we need to keep track of this
mapping.
=> Add ability to add events to sheet

DiscordBot.DataAccess/EventsSheetsService.cs
Extract metadata sheet name into a constant.
Add initialisation of metadata sheet id. For queries so far we have
been able to use its title, but to delete it we need to know its
`sheetId`. This does not change, and can be established whilst the
service is being constructed.
Implement remove events method.
=> Sheets service: remove events

DiscordBot/Commands/EventCommands.cs
The user can now edit existing events by interacting with the bot.
New features rely on GetEvent which is currently hardcoded and bugs may arise once that is implemented.
=> Add conversation for editing events

DiscordBot/Commands/EventCommands.cs
The user can now remove events by interacting with the bot.
The bot prompts the user for an event ID and asks the user for confirmation before deleting the event.
=> Add conversation for removing events

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/Models/EventResponse.cs
@kwunkiuma and I had a look at making the next part of the interface between the `EventsSheetsService` and the Discord Bot. The table structure we settled on is:
User id | :key: | :shield: | :runner: | :dart: | :clipboard: | :telescope:
-------- | ------------ | ---------- | --------- | ------- | --------- | ----------
ResponseName | Goalkeeper | Defender | Midfield | Striker | Referee | Spectator
Alice | 0 | 1 | 0 | 0 | 0 | 0
Bob | 0 | 0 | 0 | 1 | 0 | 0
Charlie | 0 | 0 | 1 | 0 | 0 | 0
David | 1 | 1 | 0 | 0 | 0 | 0
Eve | 0 | 0 | 0 | 0 | 1 | 0
The only change is that we're indexing event responses based on emoji, rather than their names. This that makes more sense with how the discord bot will be indexing events; based on emoji reactions to a message.
The two get methods correspond to …
=> Add interface to SheetsService for events signup

.gitignore
We are only using these files for secrets at the moment. If we set up
secret manager to do this then we should revert this commit.
=> Ignore launch settings

DiscordBot/Commands/EventCommands.cs
The bot can display detailed information of a specific event specified by event key.
More information (e.g. signups) will be displayed once those features are implemented.
=> Add conversation for showing an event

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/Models/DiscordEvent.cs
This will allow the discord bot to convert the IDs of messages that
have been reacted to into event keys, so it can then update responses
to that event. This message ID could be null, if the message about the
event is not published straight after creating an event.
=> Add a message ID column to event metadata

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/SheetNotFoundException.cs, DiscordBot.DataAccess/SheetsServiceRequestsHelper.cs
Also generalise the `sheetId` lookup (where sheet in this context means a single sheet among multiple in a spreadsheet document).
=> Remove response sheet on event removal

DiscordBot.DataAccess/Models/EventResponse.cs, DiscordBot/Commands/EventCommands.cs
The bot can now create a signup message for members to react to.
For now, reacting to the message doesn't do anything and the message is sent to the channel where the command is called.
=> Add signup message creation

DiscordBot/Commands/EventCommands.cs, DiscordBot/DiscordBot.csproj, DiscordBot/Program.cs
Turns out 3.x is almost obsolete so we've migrated the bot to the 4.x version.
Main changes:
- The service can now be assigned in the constructor and therefore doesn't need to be gotten every time it's needed
- Some classes were renamed
- Some class methods were renamed
=> Migrate from 3.x to 4.x

DiscordBot.DataAccess/EventsSheetsService.cs
Stop Google Sheets trying to parse the event ID as a `double` (and then
dropping precision) by writing to the sheet a `string` version of the 
ID to the sheet.
=> Bugfix for creating events

DiscordBot/Commands/EventCommands.cs, DiscordBot/Program.cs
I've converted the create command into a group command (which can utilise overloads). This means that the following things work:
?event
?event create
?event create "[name]"
?event create "[name]" "[description]"
?event create "[name]" "[description]" "[Valid DateTime]"
If any of these are missing something it will use interactivity to prompt the user to give it to them.
Whilst implementing this I removed some redundant code (the passing of the variable interactivity) so this PR does have quite a lot of small changes repeated throughout. The important changes are anything to do with group commands and the create command. The final small change was in program.cs where I needed to add intents (a 4.x thing) to give the bot permissions to read user roles (for the require roles attribute)
=> Add group command for create and fix migration issues

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/Exceptions/EventInitialisationException.cs, DiscordBot.DataAccess/Exceptions/EventNotFoundException.cs, DiscordBot.DataAccess/Exceptions/EventsSheetsException.cs, DiscordBot.DataAccess/Exceptions/EventsSheetsInitialisationException.cs, DiscordBot.DataAccess/Exceptions/ResponseNotFoundException.cs, DiscordBot.DataAccess/Exceptions/SheetNotFoundException.cs, DiscordBot.DataAccess/SheetsServiceRequestsHelper.cs
Retry using an exponential backoff when we overload our Google Sheets 
API quota instead of crashing with an unhandled exception.
=> Sheets api retries

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/SheetsServiceParsingHelper.cs, DiscordBot.DataAccess/UnsafeEventsSheetsService.cs
The new `EventsSheetsService` seems a bit repetitive but I can't think of a better way of doing it. What do you think?
=> Wrap public methods in locks to ensure atomicity

DiscordBot/Commands/EventCommands.cs
Updated the preview for starting signups and result from the show command:
Before:
After:
The create event confirmation has also been changed but lacks the event key to conserve Sheets API calls.
=> Change appearence of embeds

DiscordBot/Commands/EventCommands.cs
You can now choose between a set of hard-coded response sets for your signup as demonstrated in the image below
=> Add response set options on event creation

DiscordBot/Commands/EventCommands.cs, DiscordBot/Program.cs
The signup sheet no longer refreshes upon someone signing on/off the event.
A refresh button has been added to the signup sheet to manually refresh the sheet.
=> Add button refresh and remove automatic refresh

DiscordBot/Commands/EventCommands.cs
Listing all events will only show events that are occurring in the future.
Events are also ordered chronologically
=> Change list to only show upcoming events

DiscordBot.DataAccess/EventsSheetsService.cs, DiscordBot.DataAccess/Models/ResponseReaction.cs, DiscordBot.DataAccess/UnsafeEventsSheetsService.cs, DiscordBot/Commands/EventCommands.cs, DiscordBot/Commands/ReactionBuffer.cs, DiscordBot/Program.cs
Add a thread-safe buffer for storing reactions as they come in, and
process them up to every 10s.
Add an interface to the EventsSheetsService to process these batches
of requests. Add a model to store all information needed in a reaction:
a message (ie event) ID, a user ID and a reaction emoji (response
type).
I will implement the EventsSheetsService in another PR, and Frank
will plumb this into the Discord front end.
=> Add interface for batching event responses

DiscordBot/Commands/EventCommands.cs, DiscordBot/Program.cs
Starting a signup will now send the signup message to the channel named events.
If the channel doesn't exist then the users is informed of the error.
=> Send signup message to specific channel

DiscordBot/Commands/EventCommands.cs
I've added descriptions to all the commands and fields. Unfortunately I couldn't find a way to hide the multiple versions of CreateEvent etc so i had to just duplicate the descriptions. This is to avoid a flood of "No Description Provided" when using `?help event create`
=> Add Descriptions to commands and field for use with ?help
